// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twzjwtziaofgmhoqagdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3emp3dHppYW9mZ21ob3FhZ2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1MTE3MTUsImV4cCI6MjA1MTA4NzcxNX0.iCfR6tXe_AHxE3WbzNQKd4iBfuYcjjRDFk3IBdheuvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);